version: '2'


services:
  appserver:
    container_name: appserver
    restart: always
    build: .
    command: python ./source/server.py -l -p=test_photos -d=0.010
    ports:
      - '8080:8080'
    volumes:
      - ./source/:/src/source/